### ISSUE TITLE
[QUESTION]No working in multi page mode

### ISSUE THREAD

**Issue by xmsz** [richardtallent/vite-plugin-singlefile#17]
```
import { defineConfig } from 'vite';

import { resolve, dirname } from 'path';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { viteSingleFile } from 'vite-plugin-singlefile';
import { minifyHtml } from 'vite-plugin-html';

import { fileURLToPath } from 'url';
const ___filename = fileURLToPath(import.meta.url);
const ___dirname = dirname(___filename);

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [svelte(), viteSingleFile(), minifyHtml()],
  build: {
    target: 'es2015',
    assetsInlineLimit: 100000000,
    chunkSizeWarningLimit: 100000000,
    cssCodeSplit: false,
    brotliSize: false,
    rollupOptions: {
      inlineDynamicImports: true,
      input: {
        pure: resolve(___dirname, 'pure/index.html'),
        simple: resolve(___dirname, 'simple/index.html'),
      },
       output: {
         manualChunks: () => 'everything.js',
       },
    },
  },
});

```
It compse all the js files
```
dist/pure/index.html             4.08 KiB
dist/simple/index.html           4.08 KiB
dist/assets/pure.d4df3b1d.js     3.68 KiB
dist/assets/style.4513d045.css   0.13 KiB
```

**Comment by richardtallent** [comment]
Hi @xmsz,

I don't use Svelte and I'm not familiar with its multi-page mode. It's possible the relative path of the assets is not being considered since the assets are in a sibling folder rather than a subfolder of the `index.html` files.

I made an adjustment and bumped the version to 0.6.3. Please let me know if it fixes your issue.

If it doesn't, please edit your `npm_modules/vite-plugin-singlefile/index.js` file to add a `console.log()` entry inside the `for` loop to write out `o.value`, comment back with that results, and also include the contents of one of those `index.html` files.

**Comment by xmsz** [comment]
> Hi @xmsz,
> 
> I don't use Svelte and I'm not familiar with its multi-page mode. It's possible the relative path of the assets is not being considered since the assets are in a sibling folder rather than a subfolder of the `index.html` files.
> 
> I made an adjustment and bumped the version to 0.6.3. Please let me know if it fixes your issue.
> 
> If it doesn't, please edit your `npm_modules/vite-plugin-singlefile/index.js` file to add a `console.log()` entry inside the `for` loop to write out `o.value`, comment back with that results, and also include the contents of one of those `index.html` files.

I think promble comes from 
```
 rollupOptions: {
      output: {
        manualChunks: () => 'everything.js',
      },
    },

```

It makes all pages assets into one file


This is my demo
https://github.com/xmsz/demo-2022010101

**Comment by zunamo** [comment]
@richardtallent @xmsz any updates on this topic by any chance? I am running into the same problem. It creates 2 html files but both of them have the exact same content.

**Comment by xmsz** [comment]
> @richardtallent @xmsz any updates on this topic by any chance? I am running into the same problem. It creates 2 html files but both of them have the exact same content.

nothing updated

**Comment by richardtallent** [comment]
This is the *single file* plugin. Not the multi-file plugin. I don't understand the use case or what changes it would require, but I suspect it would be significant.

**Comment by zunamo** [comment]
I was following this example to create a figma widget and it was using your plugin:
https://github.com/figma/widget-samples/tree/main/create-widget-app

As described here, you can add multiple UIs, but they have to be single html files including the js.
https://www.figma.com/widget-docs/widget-manifest/#ui

So I was expecting that by adding 2 inputs in the config, I would also get 2 single file outputs.
As I said in a previous comment, it creates 2 outputs but they seem identical instead of having their own js code.

**Comment by omnjpa27516** [comment]
Feature request, support for mpa and vite3 @richardtallent

**Comment by richardtallent** [comment]
Please provide a testable example in a separate Issue. I don't use MPAs, so I don't have any frame of reference for understanding what issues might be coming up with them.

I am using Vite 3, but haven't tested it with this package yet.

**Comment by omnjpa27516** [comment]
peer vite 2.9

**Comment by aaronrogers** [comment]
@zunamo, did you come up with a solution for this?

**Comment by zunamo** [comment]
@aaronrogers I ended up using 1 ui file and conditionally show the content needed.

**Comment by aaronrogers** [comment]
> @aaronrogers I ended up using 1 ui file and conditionally show the content needed.

Bummers, that's what I was thinking of doing as well.

Thanks!
